services:
    mblog.authentication_success_handler:
        class: AdminBundle\EventListener\AuthenticationSuccessHandler
        arguments: ['@security.context', "@=service('doctrine').getRepository('AdminBundle:SystemEvent')"]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }