admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
