<?php

namespace AdminBundle\Repository;

use AdminBundle\Entity\SystemEvent;

/**
 * SystemEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemEventRepository extends \Doctrine\ORM\EntityRepository
{
    public function save(SystemEvent $systemEvent)
    {
        $this->_em->persist($systemEvent);
        $this->_em->flush();
    }
}
